### ISSUE TITLE
[Feature]: please make this wonderful process working before detailer

### ISSUE THREAD

**Issue by neoraoz** [Gourieff/sd-webui-reactor#218]
### Feature description

First of all, many thanks to your great efforts.

I'm askng to change the sequence of process of reactor applying before the detailer process..
At a moment, after the detailer, such as adetailer, is applied then the reactor is applying. And definitely, this dramatically reduces the qualty of face. The face restoration is far less effective than the detailer, as we all aware.

**Comment by Gourieff** [comment]
A1111 builds this sequence according to the extensions order inside the extensions folder
Just rename ReActor's folder from "sd-webui-reactor" to "0_reactor" and that's it :) A1111 will execute ReActor then ADetalier
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/67516278-327a-4296-9df6-b1ac4301ed51)

And don't forget to set "Save Original" off, otherwise ADetailer will run first:
<img src="https://github.com/Gourieff/sd-webui-reactor/assets/85128026/9e6a6e9b-b640-4962-9a96-c963ef757d4c" width=50%>

**Comment by marshy919** [comment]
Very good to know that changing the name is able to change the extension order.
Seems with adetailer after it just changes the face entirely though. 
Any success with changing the order? Am I just changing denoising strength?

**Comment by Gourieff** [comment]
Yes, denoising strength should be low - otherwise ADetailer completely changes the face

**Comment by neoraoz** [comment]
MANY MANY THANKS, It works! problem solved.

**Comment by drnod** [comment]
I am not sure. But since last update (0.6.1 BETA2) this seems not to work anymore.

Reactor is always the last inpainter. So, something applied to face, for example freckles, are overwritten by the swapped face.

Can someone confirm this?
