### ISSUE TITLE
[Feature]: add trying to halve 'det_size' parameter to face model building

### ISSUE THREAD

**Issue by thezveroboy** [Gourieff/sd-webui-reactor#247]
### Feature description

when we use very close portraits, the plugin cannot recognize faces. then it automatically uses half-frame. but this feature is not used when we try to build a model of this face. is it possible to add this feature?

**Comment by thewayur** [comment]
can anyone please explain the benefits of it? and in which scenario it is best to disable (if possible)

**Comment by Gourieff** [comment]
> can anyone please explain the benefits of it? and in which scenario it is best to disable (if possible)

When we build a face model of a small face - there can be the situation when the script cannot recognize the face and it needs to halve the det_size parameter of the detection area
I simply forgot about this point, this is not very common situation because when we build face models we don't choose bad photos or photos with a small face for this case, but what if there's no any close photo of the person - the script must work in such points too
So, I will for sure fix this in future updates

**Comment by drnod** [comment]
Just had the same issue.

Would be great to have this included in face model building.
