### ISSUE TITLE
PLS DONT COMPLICATE THE INSTALLATION 

### ISSUE THREAD

**Issue by Thanh1122kkll** [Gourieff/sd-webui-reactor#257]
### Feature description

Dear Gourieff
can you please write in big letters 'When downloading Visual Studio, choose the type that only includes C++, or provide only the most accurate download link to VISUAL STUDIO SETUP'. When visiting the website, there are hundreds of pop-up versions, and the most prominent thing that catches the eye is the software that's not right, I fiddled around adjusting and checking the code for a whole day before I could resolve it. Your node, if it's not easy to install, please don't complicate matters further for the user

**Comment by Gourieff** [comment]
This is because the Insightface library (to be built successfully) needs C++ BT
But if you don't want to install C++ BT there's the option in the instruction:

**A1111:**
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/61546f84-3ff2-4d72-98ba-feb6678d5188)

**ComfyUI:**
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/0637a268-d4a2-4cef-8262-1a5a7f426e6f)

Easy and quick steps :)
