### ISSUE TITLE
ReActor - STATUS - No target face found for 0

### ISSUE THREAD

**Issue by Redxlabel** [Gourieff/sd-webui-reactor#40]
A problem has appeared: when generating using Roop (ReActor), something like this is generated every time with every model:
https://prnt.sc/k5Xpg5zDYZiX

At the same time, the same problem when generating without Roop, seems like the entire SD was broken. Automatic1111 is in use. Updating the plugin didn't help.

In the command line, the generation slider is first filled to 100%:
https://prnt.sc/QxhFLvcFpTnn 

Then, after the generation, two lines and two sliders appear after it:
https://prnt.sc/EwLl6sZfBN_o

As if in the picture where the face should be taken from, there is no face, but it is there.

Updating the plugin with sd-webui-extensions-updater-main didn't help.

How to fix this?

**Comment by Gourieff** [comment]
Show please your workflow (specific LoRAs? embeddings? vae?), what GPU you have and how much VRAM, also show please your webui-user start file
What settings do you have at the "Optimizations" section of the Settings menu?

There can be a batch of reasons of such behavior

The most simple way is just to restart sd-webui or reboot your PC, maybe there's something wrong with a GPU driver and the reboot will help

Also you can try to write a very simple prompt, something like:
```
symmetrical portrait of beautiful woman in the green garden

neg: bad image, low quality, ugly, disproportional
```
Without any LoRAs and embeddings

The cause of this issue is not the ReActor or Roop extension
ReActor/Roop works with an already generated image
In your case ReActor gets image that contains no face and therefore ReActor does nothing with the image
