### ISSUE TITLE
Faceswap.py error occurred

### ISSUE THREAD

**Issue by li258w** [Gourieff/sd-webui-reactor#65]
I have been working normally before. Two days ago, I cleaned up the garbage from Win11 and ReActor couldn't run anymore. The following error was reported:

22:28:07- ReActor - STATUS - Working: source face index [0], target face index [0]
*** Error running postprocess_image: E:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 184, in postprocess_image
        result: ImageResult = swap_face(
      File "E:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 123, in swap_face
        source_face = get_face_single(source_img, face_index=0)
      File "E:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 76, in get_face_single
        face_analyser = insightface.app.FaceAnalysis(name="buffalo_l", providers=providers)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
        assert 'detection' in self.models
    AssertionError

I tried:
1. Reinstall ReActor
2. Close all extensions
3. Completely reinstall Stable diffusion
Report all the same errors. 

May I ask what is the solution?

**Comment by Gourieff** [comment]
According to the log - I think you use (or used) the pretty old version of ReActor

But you got this error because you might have deleted a rather important directory `%USERPROFILE%\.insightface`
If it is - try to download this archive https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip and put all the models from it to the directory `%USERPROFILE%\.insightface\models\buffalo_l`

And I recommend you to update ReActor extension to the latest version (I'm confused by the name of the folder "sd-webui-roop" - why is it not "sd-webui-reactor"?) - so, just in case:
* Go to the folder `E:\stable-diffusion-webui\extensions\sd-webui-roop` or `E:\stable-diffusion-webui\extensions\sd-webui-reactor` (if you've already reinstalled it and got the correct name of this repo)
* Open Console there (cmd) and run `git pull`
* If everything is ok, you will see a pulling process without any errors and warnings

**Comment by Gourieff** [comment]
@li258w try to update to the latest version. All the missed models will be downloaded again and be placed in the new location (inside the sd-webui directory).

**Comment by drantini** [comment]
@Gourieff I am experiencing almost the same error but on the latest version

**Comment by drantini** [comment]
nevermind, i found out the files from buffalo_l were missing for whatever reason, after uploading them it works.
For future with people with same issue they are supposed to be in: /models/insightface/models/buffalo_l
